export const FETCH_PRODUCTS_REQUESTED = 'FETCH_PRODUCTS_REQUESTED'
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'

export const requestProducts = () => ({
  type: FETCH_PRODUCTS_REQUESTED
})